apiVersion: v1
kind: Pod
metadata:
  name: app
  labels:
    name: app
spec:
  containers:
  - name: c1
    image: busybox
    command: ['sh', '-c', 'ls ; date ; sleep 5 ; date']
  - name: c2
    image: busybox
    command: ['sh', '-c', 'echo Hello World! ; date ; sleep 5 ; date']
  - name: c3
    image: busybox
    command: ['sh', '-c', 'echo Este es el 3er contendor ; date ; sleep 5 ; date']
  restartPolicy: Never