apiVersion: v1
items:
- apiVersion: extensions/v1beta1
  kind: ReplicaSet
  metadata:
    annotations:
      deployment.kubernetes.io/desired-replicas: "5"
      deployment.kubernetes.io/max-replicas: "7"
      deployment.kubernetes.io/revision: "1"
    creationTimestamp: "2020-04-16T03:21:18Z"
    generation: 3
    labels:
      app: webapp
      pod-template-hash: 7fc499b78b
    name: webapp-7fc499b78b
    namespace: default
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: Deployment
      name: webapp
      uid: bdcf6a99-8f91-4ac4-9fe3-d7437c93079c
    resourceVersion: "54762"
    selfLink: /apis/extensions/v1beta1/namespaces/default/replicasets/webapp-7fc499b78b
    uid: 509f860a-8fb4-4168-b855-c64cbfdb904f
  spec:
    replicas: 5
    selector:
      matchLabels:
        app: webapp
        pod-template-hash: 7fc499b78b
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: webapp
          pod-template-hash: 7fc499b78b
      spec:
        containers:
        - image: nginx
          imagePullPolicy: Always
          name: nginx
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 5
    fullyLabeledReplicas: 5
    observedGeneration: 3
    readyReplicas: 5
    replicas: 5
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
